### ISSUE TITLE
Running the unit tests

### ISSUE THREAD

**Issue by juancarlosjr97** [tsugicontrib/lmstest#1]
Hi, I am learning about LTI 1.3. I have implemented LTI 1.1 but I am trying to upgrade to 1.3 and Deep Linking. 

Testing this repository, I cannot find config.php, therefore I can't do any testing

![image](https://user-images.githubusercontent.com/36451129/58177978-3e649680-7c9d-11e9-9e04-927e4481b145.png)

Thank you

**Comment by francois-opencollab** [comment]
Situation is still the same, following up with Developer.

**Comment by csev** [comment]
This is not a stand alone tool - it is intended to be installed within a working Tsugi server as a module.
